import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/Navbar";
import Star from "./components/Star"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata = {
  title: "Gobinda Bauri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="layout-container"> {/* Wrapper div */}
          <Star />
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
